[ERROR] 2024-08-26 17:32:55.128 [http-nio-8088-exec-1] RedmineClient - exception while fetching issue for id: 280, ex: org.springframework.web.client.HttpClientErrorException$Forbidden: 403 Forbidden: [no body]
[INFO ] 2024-08-26 17:32:58.583 [main] SupportModuleApplication - Starting SupportModuleApplication using Java 11.0.22 on Radhays-MBP with PID 55904 (/Users/radhayanand/support-module/target/classes started by radhayanand in /Users/radhayanand/support-module)
[INFO ] 2024-08-26 17:32:58.588 [main] SupportModuleApplication - No active profile set, falling back to 1 default profile: "default"
[INFO ] 2024-08-26 17:33:03.361 [main] SupportModuleApplication - Started SupportModuleApplication in 4.983 seconds (JVM running for 5.66)
[ERROR] 2024-08-26 17:33:08.078 [http-nio-8088-exec-2] RedmineClient - exception while fetching issue for id: 280, ex: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "assigned_to" (class com.gl.ceir.supportmodule.dto.Issue), not marked as ignorable (24 known properties: "total_spent_hours", "priority", "custom_fields", "author", "subject", "done_ratio", "attachments", "total_estimated_hours", "status", "created_on", "tracker", "project", "id", "description", "category", "updated_on", "start_date", "estimated_hours", "is_private", "closed_on", "due_date", "journals", "spent_hours", "uploads"])
 at [Source: (String)"{"issue":{"id":280,"project":{"id":1,"name":"EIRS"},"tracker":{"id":2,"name":"Feature"},"status":{"id":3,"name":"Resolved","is_closed":false},"priority":{"id":2,"name":"Normal"},"author":{"id":21,"name":"Sophara Poch"},"assigned_to":{"id":7,"name":"Rakesh Hooda"},"subject":"Ticket #113_MDR UI Issues and feedback","description":"Dear team.\r\nDMC raised issue as below.\r\nPlease look into Feedback for MDR UI\r\n1. In History of update device, why action is displayed? There is no specific purpose "[truncated 7620 chars]; line: 1, column: 235] (through reference chain: com.gl.ceir.supportmodule.dto.RedmineResponse["issue"]->com.gl.ceir.supportmodule.dto.Issue["assigned_to"])
[INFO ] 2024-08-26 17:35:27.551 [main] SupportModuleApplication - Starting SupportModuleApplication using Java 11.0.22 on Radhays-MBP with PID 56219 (/Users/radhayanand/support-module/target/classes started by radhayanand in /Users/radhayanand/support-module)
[INFO ] 2024-08-26 17:35:27.555 [main] SupportModuleApplication - No active profile set, falling back to 1 default profile: "default"
[INFO ] 2024-08-26 17:35:31.993 [main] SupportModuleApplication - Started SupportModuleApplication in 4.615 seconds (JVM running for 5.103)
[INFO ] 2024-07-20 21:13:00.201 [main] SupportModuleApplicationTests - Starting SupportModuleApplicationTests using Java 11.0.22 on Radhays-MBP with PID 95022 (started by radhayanand in /Users/radhayanand/support-module)
[INFO ] 2024-07-20 21:13:00.202 [main] SupportModuleApplicationTests - The following 1 profile is active: "mysql"
[INFO ] 2024-07-20 21:13:04.606 [main] SupportModuleApplicationTests - Started SupportModuleApplicationTests in 4.523 seconds (JVM running for 8.293)
[INFO ] 2024-07-20 21:34:14.283 [main] SupportModuleApplicationTests - Starting SupportModuleApplicationTests using Java 11.0.22 on Radhays-MBP with PID 97924 (started by radhayanand in /Users/radhayanand/support-module)
[INFO ] 2024-07-20 21:34:14.285 [main] SupportModuleApplicationTests - The following 1 profile is active: "mysql"
[INFO ] 2024-07-20 21:34:45.338 [main] SupportModuleApplicationTests - Starting SupportModuleApplicationTests using Java 11.0.22 on Radhays-MBP with PID 98319 (started by radhayanand in /Users/radhayanand/support-module)
[INFO ] 2024-07-20 21:34:45.339 [main] SupportModuleApplicationTests - The following 1 profile is active: "mysql"
[INFO ] 2024-07-20 21:34:48.722 [main] SupportModuleApplicationTests - Started SupportModuleApplicationTests in 34.571 seconds (JVM running for 37.352)
[ERROR] 2024-07-20 21:34:52.135 [main] DbConnectionChecker - alert1301: DB connection failed for app while getting DB configuration value
[INFO ] 2024-07-20 21:34:54.622 [main] SupportModuleApplicationTests - Started SupportModuleApplicationTests in 9.404 seconds (JVM running for 10.083)
[ERROR] 2024-07-20 21:34:55.643 [main] DbConnectionChecker - alert1301: DB connection failed for app while getting DB configuration value
